sudo: required
language: node_js

env:
  - BUILD_JOB_TYPE=test truffle_test_file=test/clock.js
  - BUILD_JOB_TYPE=test truffle_test_file=test/loyalty.js
  - BUILD_JOB_TYPE=test truffle_test_file=test/hold.js
  - BUILD_JOB_TYPE=report

node_js:
  - "8"

before_install:
  - export PATH=./node_modules/.bin:$PATH

script:
  - "yarn run $BUILD_JOB_TYPE"

cache:
  yarn: true
  directories:
    - "node_modules"
